USE JFS15;

CREATE TABLE EMPDETAILS (
	ID INT,
    NAME VARCHAR(30),
    SALARY INT 
);

CREATE TABLE MARITIALSTATUS(
	ID INT,
    NAME VARCHAR(30),
    STATUS VARCHAR(40)
);

INSERT INTO EMPDETAILS VALUES (1,"JOHN",40000),(2,"ALEX",25000),(3,"SIMON",43000);

INSERT INTO MARITIALSTATUS VALUES (1,"JOHN","MARRIED"),(2,"SIMON","MARRIED"),(4,"STELLA","UNMARRIED");

SELECT * FROM EMPDETAILS;

SELECT * FROM MARITIALSTATUS;

-- INNER JOIN

SELECT EMPDETAILS.ID FROM EMPDETAILS
INNER JOIN MARITIALSTATUS ON 
EMPDETAILS.ID = MARITIALSTATUS.ID;

SELECT EMPDETAILS.ID,EMPDETAILS.NAME FROM EMPDETAILS
INNER JOIN MARITIALSTATUS ON 
EMPDETAILS.ID = MARITIALSTATUS.ID;

SELECT * FROM EMPDETAILS
INNER JOIN MARITIALSTATUS ON 
EMPDETAILS.ID = MARITIALSTATUS.ID;

-- LEFT JOIN

SELECT * FROM EMPDETAILS
LEFT JOIN MARITIALSTATUS ON
EMPDETAILS.ID = MARITIALSTATUS.ID;

-- RIGHT JOIN

SELECT * FROM EMPDETAILS 
RIGHT JOIN MARITIALSTATUS ON
EMPDETAILS.ID = MARITIALSTATUS.ID;

SELECT EMPDETAILS.ID,EMPDETAILS.NAME,EMPDETAILS.SALARY,MARITIALSTATUS.STATUS  FROM EMPDETAILS 
RIGHT JOIN MARITIALSTATUS ON
EMPDETAILS.ID = MARITIALSTATUS.ID;

-- SELF

CREATE TABLE ABCD(
	C1 VARCHAR(10),
	NAME VARCHAR(30),
	C2 VARCHAR(10)
);

INSERT INTO ABCD VALUES ("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");

SELECT Y.NAME,X.NAME FROM ABCD AS X, ABCD AS Y
WHERE X.C1=Y.C2;

-- CROSS JOIN

CREATE TABLE HAIR_TYPE(
	COL1 VARCHAR(10)
);

CREATE TABLE HAIR_STYLE(
	COL2 VARCHAR(10)
);

INSERT INTO HAIR_TYPE VALUES ("A"),("B"),("C");

INSERT INTO HAIR_STYLE VALUES ("STRAIGHT"),("CURLY");

SELECT COL1,COL2 FROM HAIR_TYPE CROSS JOIN HAIR_STYLE;

SELECT COL1,COL2 FROM HAIR_TYPE,HAIR_STYLE;

-- OUTER

SELECT * FROM EMPDETAILS
LEFT JOIN MARITIALSTATUS ON
EMPDETAILS.ID = MARITIALSTATUS.ID
UNION
SELECT * FROM EMPDETAILS
RIGHT JOIN MARITIALSTATUS ON
EMPDETAILS.ID = MARITIALSTATUS.ID