-- CREATION OF DATA BASE

CREATE DATABASE JFS15;
USE JFS15;

-- DDL [CREATE,ALTER,DROP]

-- CREATE

CREATE TABLE EMPLOYEE(
	SNO INT,
	NAMEE  VARCHAR(30),
    SALARY INT,
    HEIGHT FLOAT
);

SHOW TABLES;

-- ALTER

-- ADDING SINGLE COLUMN

ALTER TABLE EMPLOYEE ADD MOBILE_NUMBER INT;

DESCRIBE EMPLOYEE;

DESC EMPLOYEE;

-- ADD MULTIPLE COLUMNS AT A TIME

ALTER TABLE EMPLOYEE ADD (
	DEPT CHAR(3),
    PLACE VARCHAR(40),
    AGE INT
);

DESC EMPLOYEE;

-- DROP COLUMN

ALTER TABLE EMPLOYEE DROP COLUMN HEIGHT;

DESC EMPLOYEE;

ALTER TABLE EMPLOYEE DROP COLUMN SALARY;

DESC EMPLOYEE;

-- MODIFY DATA TYPES

ALTER TABLE EMPLOYEE MODIFY COLUMN NAMEE VARCHAR(60);

DESC EMPLOYEE;

ALTER TABLE EMPLOYEE MODIFY COLUMN DEPT VARCHAR(20);

DESC EMPLOYEE;

-- DROP

DESC EMPLOYEE;

DROP TABLE EMPLOYEE;

DESC EMPLOYEE;

-- DML

CREATE TABLE STUDENTS(
	SNO INT,
    NAMEE VARCHAR(30),
    AGE INT,
    MARKS INT,
    MOBILE INT,
    ADDRESS VARCHAR(50)
);

-- INSERT (1)

DESC STUDENTS;

INSERT INTO STUDENTS (SNO,NAMEE,AGE,MARKS) VALUES (1,"SAI",23,180);

-- INSERT(2)

INSERT INTO STUDENTS (SNO,NAMEE,AGE,MARKS) VALUES (2,"S1",10,120),(3,"S2",11,120),(4,"S3",12,121);

-- INSERT(3)

INSERT INTO STUDENTS VALUES (6,"ABC",24,90,1234567890,"HYD");

-- INSERT(4)

INSERT INTO STUDENTS VALUES (7,"DEF",24,90,1234567890,"TEL"),(8,"GHI",45,56,12345678,"AP");

-- INSERT(5)

CREATE TABLE ABC(
	SNO INT,
    NAMEE VARCHAR(30),
    AGE INT,
    MARKS INT,
    MOBILE INT,
    ADDRESS VARCHAR(50)
);  

SELECT * FROM ABC;

INSERT INTO ABC VALUES (100,"SAI VARDHAN",27,450,1234567890,"HYD");

INSERT INTO ABC (SNO,NAMEE,AGE,MARKS,MOBILE,ADDRESS) SELECT SNO,NAMEE,AGE,MARKS,MOBILE,ADDRESS FROM STUDENTS;

SELECT * FROM ABC;

CREATE TABLE FINAL (
	ROLL INT,
    STUDENT_NAME VARCHAR(50),
    MARKS INT 
);

INSERT INTO FINAL (ROLL,STUDENT_NAME,MARKS) SELECT SNO,NAMEE,MARKS FROM ABC WHERE MARKS >= 120;

SELECT * FROM FINAL;