USE JFS15;

CREATE TABLE EMP(
	ID INT PRIMARY KEY,
    FNAME VARCHAR(30),
    LNAME VARCHAR(30),
    DEPT VARCHAR(30),
    SALARY INT 
);

INSERT INTO EMP VALUES (1,"SAI","T","PYTHON",40000),(2,"VIVEK","K","PYTHON",30000),(3,"SAMUEL","H","PYTHON",60000);
INSERT INTO EMP VALUES (4,"MALLI","K","JAVA",60000),(5,"SUDHEER","H","JAVA",70000),(6,"VAMSI","L","JAVA",80000);
INSERT INTO EMP VALUES (7,"JOHN","T","DS",70000),(8,"VIVEK","K","DS",30000),(9,"SAMUEL","H","DS",60000);

SELECT * FROM EMP;
-- COUNT
SELECT COUNT(*) FROM EMP WHERE DEPT="PYTHON";
-- SUM
SELECT SUM(SALARY) FROM EMP WHERE DEPT="JAVA";
-- MAX
SELECT MAX(SALARY) FROM EMP WHERE DEPT="DS";
-- MIN
SELECT MIN(SALARY) FROM EMP WHERE DEPT="PYTHON";
-- AVG
SELECT AVG(SALARY) FROM EMP WHERE DEPT="JAVA";
-- GROUP BY
SELECT SUM(SALARY) FROM EMP; 
SELECT ID,SUM(SALARY) FROM EMP GROUP BY ID;
-- HAVING
SELECT ID,SUM(SALARY) FROM EMP GROUP BY ID HAVING SUM(SALARY)>50000;
SELECT ID,FNAME,SUM(SALARY) FROM EMP GROUP BY ID HAVING SUM(SALARY)>50000;

-- DISTINCT
SELECT DISTINCT DEPT FROM EMP;
SELECT DISTINCT SALARY FROM EMP;

-- ORDER BY
SELECT SALARY FROM EMP ORDER BY SALARY ASC;
SELECT SALARY FROM EMP ORDER BY SALARY DESC;
SELECT DISTINCT SALARY FROM EMP ORDER BY SALARY DESC;
SELECT DISTINCT SALARY FROM EMP ORDER BY SALARY ASC;
SELECT * FROM EMP ORDER BY SALARY DESC;







