USE JFS15;

SHOW TABLES;

SELECT * FROM DETAILS;

-- ARITHEMETIC OPERATORS

SELECT SNO,NAME,AGE,(AGE+2) AS UPDATED_AGE FROM DETAILS;
SELECT SNO,NAME,AGE,(AGE-2) AS UPDATED_AGE FROM DETAILS;
SELECT (SNO*100) AS SNO,NAME,AGE FROM DETAILS;
SELECT SNO,NAME,AGE,(AGE/2) FROM DETAILS;
SELECT SNO,NAME,AGE,(AGE%2) AS CHECKING FROM DETAILS WHERE (AGE%2=0);

-- COMPARISION OPERATORS

SELECT * FROM DETAILS;
SELECT * FROM DETAILS WHERE AGE = 56;
SELECT * FROM DETAILS WHERE AGE != 56;
SELECT * FROM DETAILS WHERE AGE > 56;
SELECT * FROM DETAILS WHERE AGE < 56;
SELECT * FROM DETAILS WHERE AGE >= 56;
SELECT * FROM DETAILS WHERE AGE <= 56;

-- LOGICAL OPERATORS

SELECT * FROM DETAILS;
SELECT * FROM DETAILS WHERE SNO%2=0 AND AGE>=56;
SELECT * FROM DETAILS WHERE SNO%2=0 OR AGE < 56;
SELECT * FROM DETAILS WHERE NOT AGE >= 56;

-- NULL OPERATOR
SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE (ID,NAMEE) VALUES (3,"VENKAT"),(4,"AJAY");
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE STREAM IS NULL;
SELECT * FROM EMPLOYEE WHERE STREAM IS NOT NULL;