USE JFS15;

-- STRING LENGTH
SELECT LENGTH("SAI VARDHAN") AS NEW_NAME;
SELECT CHAR_LENGTH("SAI VARDHAN");
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LENGTH(NAMEE) > 3;
INSERT INTO EMPLOYEE VALUES (5,"ABC","CIVIL");
SELECT * FROM EMPLOYEE WHERE LENGTH(STREAM)!=3;

-- SUBSTRING
SELECT SUBSTRING("ABCDEFGH",3,4);
SHOW TABLES;
SELECT * FROM DETAILS;
CREATE TABLE DETAILS1(
	FNAME VARCHAR(10),
    LNAME VARCHAR(20)
);
INSERT INTO DETAILS1 VALUES ("SAI","VARDHAN"),("VISHNU","VARDHAN"),("HARSHA","VARDHAN");
SELECT * FROM DETAILS1;
SELECT FNAME,LNAME,SUBSTRING(FNAME,1,3) AS P1,SUBSTRING(LNAME,3) AS P2 FROM DETAILS1;
SELECT FNAME,LNAME,CONCAT(SUBSTRING(FNAME,1,3),SUBSTRING(LNAME,3)) AS PASSWORD FROM DETAILS1;

-- REVERSE
SELECT REVERSE("SAI") AS REVERSED;
SELECT FNAME,REVERSE(FNAME) AS REVERSED_FNAME FROM DETAILS1;
INSERT INTO DETAILS1 VALUES ("WOW","HERO");
SELECT * FROM DETAILS1;
SELECT * FROM DETAILS1 WHERE FNAME=REVERSE(FNAME);

-- REPLACE
SELECT REPLACE("SAI VARDHAN","SAI","BYE");
SELECT * FROM DETAILS1;
SELECT *,REPLACE(LNAME,"VARDHAN","V") AS REPLACED_STRING FROM DETAILS1;

-- LIKE

CREATE TABLE D(
	FNAME VARCHAR(30),
    EMAIL VARCHAR(40),
    MOBILE VARCHAR(40)
);
INSERT INTO D VALUES ("SAI","SAI@GMAIL.COM","789-357-0611"),("VARDHAN","VARDHAN@COM","789-357-0711");

SELECT * FROM D;
SELECT * FROM D WHERE MOBILE LIKE "___-___-____";
SELECT * FROM D WHERE FNAME LIKE "S%";


