-- 1
-- INSERT INTO TBALE_NAME [COLUMN1,COLUMN2,...] VLAUES (VALUE1,VALUE2,....)
-- UPDATE TABLENAME SET COLUMN1 = VALUE1 [WHERE CONDITION]
-- DELETE FROM TABLENAME [WHERE CONDITION] 

-- 2
-- SELECT COLUMN1,COLUMN2,.... FROM TABLENAME
-- SELECT * FROM EMPLOYEE;

-- 3
-- 3.1
-- CREATE TABLE EMPLOYEES (
-- 	NAME VARCHAR(10),
--     AGE INT,
--     GENDER CHAR(1)
-- );
-- INSERT INTO EMPLOYEES VALUES ("SAI",56,"M");
-- INSERT INTO EMPLOYEES VALUES ("VARDHAN",67,"M");
-- INSERT INTO EMPLOYEES VALUES ("HEMA",78,"F");
-- 3.2
-- CREATE USER PINKY IDENTITFIED BY 'PONKY';
-- 3.3
-- GRANT SELECT,INSERT ON EMPLOYEES TO PINKY;

-- 5
-- 5.1
-- CREATE TABLE HAPPYDAYS(
-- 	SNO INT,
--     DAYNAME VARCHAR(40)
-- );
-- 5.2
-- START TRANSACTION
-- INSERT INTO HAPPYDAYS VALUES (1,"MONDAY"),(2,"TUESDAY"),(3,"WEDNESDAY"),(4,"THURSDAY"),(5,"SUNDAY");
-- ROLLBACK
-- 5.3
-- START TRANSACTION;
-- INSERT INTO HAPPYDAYS VALUES (1,"MONDAY");
-- INSERT INTO HAPPYDAYS VALUES (2,"WEDNESDAY");
-- SAVEPOINT AA;
-- INSERT INTO HAPPYDAYS VALUES (3,"SATURDAY");
-- INSERT INTO HAPPYDAYS VALUES (4,"SUNDAY");
-- ROLLBACK TO AA;



