USE JFS15;
SHOW TABLES;

-- BETWEEN
SELECT * FROM DETAILS;
INSERT INTO DETAILS VALUES (6,"NEW2",102),(7,"NEW3",46);
SELECT * FROM DETAILS WHERE AGE >= 39 AND AGE <=89;
SELECT * FROM DETAILS WHERE AGE BETWEEN 39 AND 89;

-- IN
SELECT * FROM DETAILS WHERE AGE = 56 OR AGE=89;
SELECT * FROM DETAILS WHERE AGE IN (56,89);

-- CASE

INSERT INTO DETAILS VALUES (8,"NEW5",14),(9,"NEW6",12);
SELECT * FROM DETAILS;
SELECT *,
	CASE
		WHEN AGE >= 89 THEN "OLD" 
        WHEN AGE >= 34 THEN "YOUNG"
        ELSE "CHILD" 
	END AS DATA
FROM DETAILS;

-- STRING FUNCTIONS

CREATE TABLE ABC(
	FNAME VARCHAR(10),
    MNAME VARCHAR(20),
    LNAME VARCHAR(30),
    AGE INT
);

INSERT INTO ABC VALUES ("SAI","VARDAHN","T",34),("VENKAT","VARDHAN","S",35),("VINAY","KUMAR","H",35),("VIGNAN","RAJ","K",56);
SELECT * FROM ABC;
-- CONCAT
SELECT CONCAT(FNAME," ",MNAME," ",LNAME) AS FULL_NAME,AGE FROM ABC;
SELECT CONCAT("SAI"," ","VARDHAN") AS FNAME;
-- CONCAT_WS
SELECT CONCAT_WS(" ","SAI","VARDHAN","NAIDU") AS FULL_NAME;
SELECT CONCAT_WS(" ",FNAME,MNAME,LNAME) AS FULL_NAME,AGE FROM ABC;
SELECT CONCAT(FNAME, " " ,MNAME, "," ,LNAME) AS FULL_NAME FROM ABC;
-- LOWER
SELECT FNAME FROM ABC;
SELECT LOWER(FNAME) AS LOWER_NAME FROM ABC;
-- UPPER
SELECT * FROM DETAILS;
SELECT UPPER(NAME) AS UPPER_NAME FROM DETAILS;








    

